# Writes a C++ source that compiles viewer.html and THIRD_PARTY_NOTICES.md into
# the binary and defines soi::loadEmbeddedResource() over them -- the
# non-Windows counterpart of the RCDATA entries in src/soi-share.rc.in, so the
# binary alone is a complete program here too.
#
#   cmake -DVIEWER=<file> -DNOTICES=<file> -DOUTPUT=<file.cpp> -P EmbedResources.cmake

function(soi_embed_array path name out_var)
    file(READ "${path}" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR size "${hex_len} / 2")
    # Two hex digits per byte -> "0xNN," per byte. One long line; compilers
    # do not mind, and nobody reads this file.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    set(${out_var}
        "const unsigned char ${name}[] = {\n    ${bytes}0x00\n};\nconst size_t ${name}_size = ${size};\n"
        PARENT_SCOPE)
endfunction()

soi_embed_array("${VIEWER}"  kViewer  viewer_src)
soi_embed_array("${NOTICES}" kNotices notices_src)

set(content "// Generated by cmake/EmbedResources.cmake -- do not edit.
#include \"app/Lifecycle.h\"

#include <cstddef>
#include <string>

namespace soi {
namespace {
${viewer_src}
${notices_src}
} // namespace

bool loadEmbeddedResource(int id, std::string& out) {
    out.clear();
    if (id == kViewerResourceId)
        out.assign(reinterpret_cast<const char*>(kViewer), kViewer_size);
    else if (id == kNoticesResourceId)
        out.assign(reinterpret_cast<const char*>(kNotices), kNotices_size);
    return !out.empty();
}

} // namespace soi
")

# Only touch the file when it changes, so an unrelated reconfigure does not
# force a rebuild.
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
    if(previous STREQUAL content)
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${content}")
